name: regimelab-notebooks
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - fastparquet
  - statsmodels
  - copulas
  - pymc3
  - arviz
- pip:
    - pyeeg
